[package]
name = "repo-man"
version = "0.2.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
dirs = "6.0"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"]}
toml = "0.8"
